name: JacobBommarito
favicon: null
layout_spectrum: 0.810483159031719
typography_spectrum: 0.9921596590429544
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8133603450842202
  lightness: 0.05445097922347486
  saturation: 0.8375486477743834
  rhythmicContrast: 0.8552814964205027
purpose: []
