name: JacobBommarito
favicon: null
layout_spectrum: 0.810483159031719
typography_spectrum: 0.53748
title: Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8d0000'
    - '#9b7680'
    - '#0f3a4b'
    - '#b9b5b1'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
